payum:
    gateways:
        paypal_express_checkout:
            factory: "paypal_express_checkout"
            payum.http_client: "@sylius.payum.http_client"
            username: "%payum_username%"
            password: "%payum_password%"
            signature: "%payum_signature%"
            sandbox: "%paypal.express_checkout.sandbox%"

sylius_payment:
    gateways:
        paypal_express_checkout: Paypal Express Checkout

