payum:
    gateways:
        paypal_express_checkout:
            factory: "paypal_express_checkout"
            payum.http_client: "@sylius.payum.http_client"
            username: remi.reibel-facilitator_api1.rdm-editions.com
            password: K3YRAVDPTEZ2UTRC
            signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AllVf.16fi7jJ9w1cK9FqdXxFiCA
            sandbox: "%paypal.express_checkout.sandbox%"

sylius_payment:
    gateways:
        paypal_express_checkout: Paypal Express Checkout

