payum:
    gateways:
        paypal_express_checkout:
            factory: "paypal_express_checkout"
            payum.http_client: "@sylius.payum.http_client"
            username: "%paypal.express_checkout.username%"
            password: "%paypal.express_checkout.password%"
            signature: "%paypal.express_checkout.signature%"
            sandbox: "%paypal.express_checkout.sandbox%"
sylius_payment:
    gateways:
        paypal_express_checkout: Paypal Express Checkout