# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin_dashboard_redirect:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_admin_dashboard
        permanent: true

# Edited routing

sylius_shop_our_books:
    path: /nos-livres
    defaults:
        _controller: sylius.controller.product:booksAction

sylius_shop_aboutUs:
    path: /etre-edite
    defaults:
        _controller: sylius.controller.product:aboutUs

sylius_shop_generalConditions:
    path: /mentions-legales
    defaults:
        _controller: sylius.controller.product:generalConditions

# Sylius origin routing

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api

