#services:
 #   app.form.extension.type.product_type:
  #      class: AppBundle\Form\Extension\ProductTypeExtension
   #     tags:
    #        - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Product\ProductType }