services:
    app.form.extension.type.product_type:
        class: AppBundle\Form\Extension\ProductTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Product\ProductType }

    app.mail.order_confirmation.send:
        class: AppBundle\Listener\MailConfirmationOrder
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    twig.extension.array:
        class: Twig_Extensions_Extension_Array
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }
